language: c
dist: xenial
cache:
  apt: true
  ccache: true
  directories:
    - '$HOME/.sonar/cache'

addons:
  apt:
    packages:
    - libgl1-mesa-dev
    - libmirclient-dev
    - libwayland-dev
    - libx11-xcb-dev
    - libxcursor-dev
    - libxi-dev
    - libxinerama-dev
    - libxkbcommon-dev
    - libxrandr-dev
    - lcov
  sonarcloud:
    organization: "souryogurt-github"
    token:
      secure: "Uiav5t25keqIYTvvLgB67zV4XLXXe0mnI1Zlb/VwcuN0wuwsD4g3I3B//IGPi+ZoqU27EOG9rROgY78euy10HDytmeRW2m4xiGkmdydAVP9yZ6qNr3LCRAoQ5t4uO6yPsxBFQAONGXsgWPJSIdtvnyFLuXDLEaJdxZbPqyretRdavHPPGUCBgTn4Fwaksny+xEiamAkmKPG7YwBKbN6DvkWCcFDecxmb7ozm6MUMhemS/jONSX8kenK3GiVrPUt5Ya2SNgWZWfP2PIhd6c3ek6FW5FLsout8Wv2lAVD7xvhA30sZbIcpvaYA3lcrAJKqKR6uTB7FiDdgnG//oAReXrreWxV4y3S5wMRfU72pVQP/6OndZ76mzL0FY8usbIOWly/8Z/JHL0/a0fxAvnLE7sBpoh970xPM3C///e5n4OUBWmnVcCVdVgLL9hArLPh+V6ZjwvoPUfxCrEsCgVRAr5QAekUxBzmgu1wwo5HNqZQxP6JkB5ph/3NnPhN6krVMagDljn+MWLqY3AHzAH+e1FkIkAudw7MikhrcVcJQCI3hExbhIjEcOQ6V95lrTmmMu2qoWzIGkmpSKrqexBzfWmvqpm/wbWgLA7dQ8nTW7bCgLgcyrTDVXQmRlb3mu+mkrhIZpohqMYUJc0/IP5kchlgDpZA31maXcnBRQNmEh6A="

env:
  global:
    - LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/../local/lib:${LD_LIBRARY_PATH}

install:
    - |
        cd ${TRAVIS_BUILD_DIR}/..
        mkdir -p local/share
        cd local/share
        echo "CPPFLAGS=-I${TRAVIS_BUILD_DIR}/../local/include" >> config.site
        echo "LDFLAGS=-L${TRAVIS_BUILD_DIR}/../local/lib" >> config.site
        cd ${TRAVIS_BUILD_DIR}
    - |
        cd ${TRAVIS_BUILD_DIR}/..
        git clone --depth 1 https://github.com/KhronosGroup/Vulkan-Headers.git
        cd Vulkan-Headers
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/../local ..
        make -j $core_count install
        cd ${TRAVIS_BUILD_DIR}
    - |
        cd ${TRAVIS_BUILD_DIR}/..
        git clone --depth 1 https://github.com/KhronosGroup/Vulkan-Loader.git
        cd Vulkan-Loader
        mkdir build
        cd build
        cmake -DVULKAN_HEADERS_INSTALL_DIR=${TRAVIS_BUILD_DIR}/../local -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/../local ..
        make -j $core_count install
        cd ${TRAVIS_BUILD_DIR}
    - |
        cd ${TRAVIS_BUILD_DIR}/..
        git clone --depth 1 https://github.com/glfw/glfw.git
        cd glfw
        mkdir build
        cd build
        cmake -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/../local ..
        make -j $core_count install
        cd ${TRAVIS_BUILD_DIR}
    - |
        cd ${TRAVIS_BUILD_DIR}/..
        git clone --depth 1 https://github.com/cgreen-devs/cgreen.git
        cd cgreen
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/../local ..
        make -j $core_count install
        cd ${TRAVIS_BUILD_DIR}

before_script: autoreconf -i

script:
    - CPPFLAGS="-I/usr/include" CFLAGS="--std=gnu11 -Wall -Wextra" ./configure --enable-code-coverage --with-unit-tests --prefix=${TRAVIS_BUILD_DIR}/../local
    - build-wrapper-linux-x86-64 --out-dir bw-output make
    - VERBOSE=1 make check
    - gcov -a -c topdax/*.o renderer/*.o
    - git fetch --unshallow
    - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    - git fetch origin
    - sonar-scanner
